
version: 2
models:
  - name: my_first_dbt_model_2
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
          - accepted_values : 
              values : [1,2,3,4]
              quote : false